name: gh-pages-deploy

on:
  pull_request:
    branches:
      - master

env: 
  NUXT_APP_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}} 
  NUXT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
  NUXT_APP_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
  NUXT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
  NUXT_APP_FIREBASE_MESSAGE_SENDER_ID: ${{secrets.FIREBASE_MESSAGE_SENDER_ID}}
  NUXT_APP_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
  NUXT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist